r"""How to write summaries that stand alone: read before summarizing a conversation, meeting, PR, paper, or repo change for a human reader.

# Writing Summaries That Stand Alone

Guidelines for summarizing any long source: a meeting transcript, a chat thread, a review discussion, a diff, a paper. The summary is the only thing the reader will read. write-docs covers the sentences. This skill covers what the summary says. Apply both.

A source records what was said, in the order it was said. The reader wants to know what is now true: what was decided, what is still open, who is doing what, and why. A good summarizer builds a picture of the situation from the source and writes from the picture. A bad summarizer shortens the source.

Here is a passage from the minutes of a Federal Open Market Committee meeting. The minutes compress a day of committee discussion into a few pages. This is the standard summaries here should default to:

> The manager turned first to an overview of broad market developments during the intermeeting period.[1] Respondents to the Open Market Desk Survey of Market Expectations (Desk survey) continued to see the economy as resilient[4] and again marked up their forecasts for real gross domestic product (GDP) growth in 2026, while their expectations for headline personal consumption expenditures (PCE) inflation and the unemployment rate were little changed. Market- and survey-based policy rate expectations were likewise little changed. Market-based measures of policy rate expectations indicated one to two 25 basis point rate cuts this year, and the median modal path of the federal funds rate, as given in the Desk survey, continued to indicate expectations of two 25 basis point rate cuts this year.
>
> The manager turned next to Treasury market developments and market-based measures of inflation compensation. Shorter-term Treasury yields were little changed, while longer-term yields rose a few basis points on net; the Treasury curve steepened slightly as a result. Near-term inflation compensation continued to decline amid lower-than-expected consumer price index (CPI) readings, lower energy prices, and lower-than-anticipated pass-through of tariffs to customers; forward rates suggested that near-term inflation would stabilize close to current levels for the rest of the year. Model-based measures of short-term inflation expectations also declined some over the intermeeting period, with forward rates suggesting further modest declines over the course of this year. The Treasury market continued to function well amid low volatility. In light of the growing portion of Treasury securities that is financed using repos, the manager noted the importance of the stability of the repo market for the continued smooth functioning of the Treasury market.[5]
>
> The recent announcement that Fannie Mae and Freddie Mac may increase their mortgage investment portfolios[8] garnered substantial market attention and was followed by a notable decline in mortgage-backed securities yields relative to those on comparable-maturity Treasury yields.[9] Still, the manager observed that the decline was unlikely to result in a material increase in mortgage refinancing because current mortgage rates are well above the weighted average rate of outstanding mortgages.[6]

Every claim has an owner: survey respondents see the economy as resilient, market-based measures indicated one to two rate cuts, the manager noted the importance of repo stability. The last paragraph reports an event, the market's reaction, and the manager's judgment with its reason attached: refinancing is unlikely to rise, because current mortgage rates sit well above the average rate on outstanding mortgages. No one said that reason aloud in the meeting. The writer added it so the passage stands on its own.

Write like that.

Here, on the other hand, is the same briefing summarized the way summaries usually fail:

> The manager's briefing covered a range of topics, including survey results, Treasury market developments, and a recent announcement.[2] The briefing opened with the Desk survey.[1] Overall, the economy is seen as resilient, and growth forecasts were marked up again,[4] while expectations for inflation and unemployment were little changed. A considerable portion of the discussion concerned the survey itself, with an extended exchange about response rates and whether the questions on rate expectations should be reworded; participants explored several possibilities and the topic generated substantial engagement before the group moved on.[7]
>
> The briefing then turned to Treasury markets.[1] Shorter-term yields were little changed while longer-term yields rose somewhat, and near-term inflation compensation continued to decline, which was attributed to a number of factors.[4] Model-based measures moved in a manner consistent with the drivers mentioned earlier.[3] The question was raised of whether the repo market posed any risk to Treasury market functioning.[5] Attention then shifted to the recent announcement,[8] which had attracted considerable market interest; the resulting yield moves were viewed by some as significant,[4] although refinancing is not expected to increase materially.[6]
>
> Toward the end of the briefing,[1] it was noted that the announcement in question was that Fannie Mae and Freddie Mac may increase their mortgage investment portfolios, news which had been followed by a notable decline in mortgage-backed securities yields relative to comparable-maturity Treasuries.[9]

Do NOT summarize like that. Note that its prose is mostly clean: no banned words, short sentences, nothing write-docs would flag. A summary can pass every sentence-level rule and still fail completely, because what is wrong with it is what it chose to say.

The numbers refer to the [bracketed] markers in both passages. Where a number appears in each, the pair is the failing and the working version of the same thing. Tell 7 marks an absence on the good side: the real minutes give the methodology chatter no space at all, so there is nothing to mark.

1. Walking the source: the summary follows the source's own order: turn by turn through a conversation, file by file through a diff, section by section through a paper. Order by the subject instead. A spine of subjects is fine, and the minutes use one ("turned first to" follows the briefing's agenda); what fails is the clock. "The briefing opened with" and "toward the end of the briefing" preserve when things were said, which the reader never needed to know.

2. Topics without content: "we discussed the migration", "this PR refactors the auth module", "the paper explores tradeoffs in caching". Each names what the source is about and shares nothing it says. A sentence that could have been written before reading the source carries no information about it. Cash every topic out in specifics or drop it.

3. Pointers to nowhere: a reference that resolved during the conversation but resolves to nothing in the summary: "the approach discussed earlier", "the second reviewer's concern", "the drivers mentioned earlier", "see Section 3". Name the thing instead. Every reference must resolve inside the summary itself.

4. Claims with no owner: the reader cannot tell whether a statement is a fact, someone's position, or the summarizer's own guess. "The economy is seen as resilient": seen by whom? In the minutes it is survey respondents. For a paper the three cases are the authors' finding, a work they cite, and the summarizer's opinion; for a PR, what the code does, what the description promises, and what a reviewer suspects. Vague hedges are the same failure: "some concerns were raised" hides both the who and the which. Give every claim its owner, and mark your own inferences as yours.

5. No status: a thread is reported but its current state is not. Decided, dropped, or still open; merged, blocked, or awaiting review; a task with nobody named as doing it. "The question was raised" is where this tell lives: raised, and then what? The minutes commit: the manager noted repo stability matters. When the source left something open, say it is open. An honest "undecided" is status too.

6. The why dropped: the conclusion survives but its reason does not. "Refinancing is not expected to increase materially" keeps the what and loses the why; the minutes keep both, and the reason (current mortgage rates sit well above the average rate on outstanding mortgages) is what lets the reader check the logic and notice when it stops applying. Reasons are scattered in every source: across turns in a conversation, across review comments in a PR, across the introduction and discussion of a paper. Gathering them is most of the work of summarizing, which is why they are the first thing lazy summaries lose.

7. Space by bulk: space in the summary tracks the size of the source material instead of how much it matters. The twenty-minute methodology digression that changed nothing gets the longest stretch; the two-line exchange that changed everything gets half a clause; the thousand-line mechanical rename dominates a PR summary while the one-line behavior change hides at the bottom. Weight by how much each item changed the situation.

8. Assumes you read it: the summary only makes sense next to the source. "The recent announcement" is intelligible only to a reader who already knows what happened that week; the reader may never open the source and has probably forgotten it. A summary must still work a week later with the source gone. Standing alone means naming what the source introduced; it does not mean reciting background the reader already holds.

9. Buried lede: the biggest change arrives in the final sentence, because that is where the source got to it. The minutes lead with the announcement and its market reaction. Put the largest change first, where the reader cannot miss it.

Tells 1-3 are one failure: the summary is written from the source instead of from what the source describes. Tells 4-7 are a second: the picture reaches the reader with a piece missing (its owners, its status, its reasons, its proportions). Tells 8-9 are a wrong guess about what the reader holds.

The first family has fifty years of science behind it. Kintsch and van Dijk (1978) showed that readers build the gist of a text with three operations: delete what does not matter, generalize lists into a covering statement, and construct statements that were never in the text. Memory then converges on that gist as details fade, one of the most replicated results in the field. Brown and Day (1983) found that novice summarizers use only the first operation, and named the result copy-delete: run through the source in order, keep or drop each bit, and copy the kept bits in roughly their original words. That is tell 1, and it is every summarizer's default, human or LLM. The operations that make a summary worth reading are the hard ones; in Brown and Day's data, even college students usually failed to construct a covering statement where the source lacked one. The mortgage paragraph in the minutes is that hard move done well. The because-clause appears in no transcript; the writer constructed it.

Their later work explains the other two families. What a reader keeps from a text is a model of the situation it describes, built by joining the text with what the reader already knows; the exact words fade in minutes and the sentences within days (van Dijk and Kintsch, 1983). A transcript contains no such model. The situation lived in the participants' heads, which is why raw transcripts are so much work to read. The summarizer's job is to rebuild the situation from the source and write from it: what is true, who wants what and why, what is decided and what is open. And since the reader already holds a situation model of their own (the project, the people, the running argument), a summary is an update to that model, not a description for a stranger. Each tell is a way the update fails to apply: a claim with no owner cannot be trusted, a pointer to nowhere cannot be resolved, and background the reader already holds updates nothing.

Before sending, read the draft once against the four dimensions the summarization-evaluation literature settled on (SummEval; Fabbri et al., 2021). Relevance: did it pick what matters? Consistency: is every statement supported by the source, or marked as the summarizer's own? Coherence: does it read as one situation rather than a pile of fragments? Fluency: write-docs owns it. Most tells are one of these failing somewhere specific: relevance fails through tells 2, 6, and 7, consistency through 4 and 5, coherence through 1, 3, and 9. The dimension the literature lacks is the reader: no score asks whether the summary stands alone, because evaluators judge it with the source open beside it. Tell 8 is invisible to that protocol, which is a reason to check it deliberately.

The minutes are a model for their discipline, not their register. Take the habits: every claim owned, judgments committed to with their reasons attached, context added wherever the reader needs it to make sense of an event. Leave the committee-speak: "garnered substantial market attention" survives in the Fed's pages because institutions write that way, and a summary for a colleague has no such requirement; write-docs's rules on plain words apply to summaries too. And leave the anonymization. The minutes say "the manager" and "a few participants" because committee politics require it. Your reader wants names, because who holds a position is half the information: "Sam wants the migration delayed until the index rebuild ships" updates the reader's picture, and "concerns were raised about timing" does not.

When a new tell is added to this skill, add a marked instance to the sloppy passage too, and a marker to the minutes passage where a paired good version exists.
"""
